title: Estados e Cidades do Brasil (Laravel)
description: Base de dados com todos os estados e cidades do Brasil
google_analytics: 
show_downloads: true
theme: jekyll-theme-cayman

gems:
  - jekyll-mentions
